intel-compute-runtime: backport fix
fixes following build error in intel-compute-runtime-native on Ubuntu 24.04 host:
error: ‘*(const NEO::ArgDescValue::Element*)((char*)&<unnamed> + offsetof(NEO::ArgDescValue, NEO::ArgDescValue::elements.StackVec<NEO::ArgDescValue::Element, 1, unsigned char>::onStackMemRawBytes[0]))’ may be used uninitialized [-Werror=maybe-uninitialized]

Backport patch:
* 0001-fix-add-missing-zero-initialization-in-StackVec-clas.patch

Signed-off-by: Yogesh Tyagi <yogesh.tyagi@intel.com>